servinow_factura:
    resource: "@ServinowFacturaBundle/Resources/config/routing.yml"
    prefix:   /{restaurantID}/factura

servinow_gestion_pedidos:
    resource: "@ServinowGestionPedidosBundle/Resources/config/routing.yml"
    prefix:   /{restaurantID}/pedidos/
servinow_movimientos_de_caja:
    resource: "@ServinowMovimientosDeCajaBundle/Resources/config/routing.yml"
    prefix:   /{restaurantID}/caja

servinow_platos:
    resource: "@ServinowPlatosBundle/Resources/config/routing.yml"
    prefix:   /{restaurantID}/platos/

servinow_navigation:
    resource: "@ServinowNavigationBundle/Resources/config/routing.yml"
    prefix:   /{restaurantID}/

servinow_restaurant_drawer:
    resource: "@ServinowRestaurantDrawerBundle/Resources/config/routing.yml"
    prefix:   /{restaurantID}/organizador/

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
