servinow_platos_homepage:
    pattern:  /
    defaults: { _controller: ServinowPlatosBundle:Default:index }

servinow_platos_homepage_decidir:
    pattern:  /decidir
    defaults: { _controller: ServinowPlatosBundle:Default:decidir }
    
servinow_platos_homepage_editar:
    pattern:  /{platoID}/editar/
    defaults: { _controller: ServinowPlatosBundle:Default:editar }